filebeat.inputs:
- type: log
 # Change to true to enable this input configuration.
  enabled: true
  paths:
    - /var/log/nginx/*
  tags: ["nginx"]

- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  enable: true
  tags: ["docker"]

- type: syslog   # activate syslog module
  protocol.udp:
    host: "localhost:514"

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "{SERVERIP}:5601"

output.kafka:
  hosts: ["{SERVERIP2}:9092"]
  topic: 'filebeat'
  codec.format:
    string: '%{[@timestamp]} %{[message]}'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  close_inactive: 10m

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~